import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'README',
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'tutorials'}],
    },
    {
      type: 'category',
      label: 'How-to Guides',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'how-to'}],
    },
    {
      type: 'category',
      label: 'Built-in Packages',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'builtin-packages'}],
    },
    {
      type: 'category',
      label: 'Explanation',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'explanation'}],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
    {
      type: 'category',
      label: 'Developer Guide',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'developer-guide'}],
    },
    {
      type: 'category',
      label: 'Releases',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'releases'}],
    },
  ],
};

export default sidebars;
